In [260]:
import pandas as pd
import numpy as np
import sklearn

In [261]:
data = pd.read_csv('GIST_radiomicFeatures.csv')

In [262]:
data.columns.values

array(['ID', 'label', 'PREDICT_original_sf_compactness_avg_2.5D',
       'PREDICT_original_sf_compactness_std_2.5D',
       'PREDICT_original_sf_rad_dist_avg_2.5D',
       'PREDICT_original_sf_rad_dist_std_2.5D',
       'PREDICT_original_sf_roughness_avg_2.5D',
       'PREDICT_original_sf_roughness_std_2.5D',
       'PREDICT_original_sf_convexity_avg_2.5D',
       'PREDICT_original_sf_convexity_std_2.5D',
       'PREDICT_original_sf_cvar_avg_2.5D',
       'PREDICT_original_sf_cvar_std_2.5D',
       'PREDICT_original_sf_prax_avg_2.5D',
       'PREDICT_original_sf_prax_std_2.5D',
       'PREDICT_original_sf_evar_avg_2.5D',
       'PREDICT_original_sf_evar_std_2.5D',
       'PREDICT_original_sf_solidity_avg_2.5D',
       'PREDICT_original_sf_solidity_std_2.5D',
       'PREDICT_original_sf_area_avg_2.5D',
       'PREDICT_original_sf_area_max_2.5D',
       'PREDICT_original_sf_area_min_2.5D',
       'PREDICT_original_sf_area_std_2.5D',
       'PREDICT_original_sf_volume_2.5D', 'PREDICT_orig

In [263]:
data.head()

ID     label  PREDICT_original_sf_compactness_avg_2.5D  \
0  GIST-001_0      GIST                                  0.797427   
1  GIST-002_0  non-GIST                                  0.896991   
2  GIST-003_0      GIST                                  0.893238   
3  GIST-004_0  non-GIST                                  0.914027   
4  GIST-005_0  non-GIST                                  0.659747   

   PREDICT_original_sf_compactness_std_2.5D  \
0                                  0.120594   
1                                  0.045854   
2                                  0.051894   
3                                  0.032078   
4                                  0.266226   

   PREDICT_original_sf_rad_dist_avg_2.5D  \
0                              80.192445   
1                              35.323607   
2                              17.582541   
3                              21.951056   
4                              20.801224   

   PREDICT_original_sf_rad_dist_std_2.5D  \
0                               9.445741   
1                               2.781343   
2                               1.864908   
3                               2.188093   
4                               4.025831   

   PREDICT_original_sf_roughness_avg_2.5D  \
0                                7.102210   
1                                5.339906   
2                                7.622507   
3                                4.757274   
4                               14.404912   

   PREDICT_original_sf_roughness_std_2.5D  \
0                                3.876595   
1                                1.923100   
2                                1.039745   
3                                1.786309   
4                                7.695865   

   PREDICT_original_sf_convexity_avg_2.5D  \
0                                0.927623   
1                                0.975762   
2                                0.979608   
3                                0.981125   
4                                0.865275   

   PREDICT_original_sf_convexity_std_2.5D  ...  \
0                                0.081385  ...   
1                                0.017550  ...   
2                                0.017926  ...   
3                                0.013734  ...   
4                                0.171213  ...   

   PREDICT_original_phasef_phasesym_median_WL3_N5  \
0                                             0.0   
1                                             0.0   
2                                             0.0   
3                                             0.0   
4                                             0.0   

   PREDICT_original_phasef_phasesym_std_WL3_N5  \
0                                     0.032461   
1                                     0.043431   
2                                     0.068175   
3                                     0.044148   
4                                     0.043369   

   PREDICT_original_phasef_phasesym_skewness_WL3_N5  \
0                                          7.353902   
1                                          6.452863   
2                                          3.849719   
3                                          5.725807   
4                                          4.546357   

   PREDICT_original_phasef_phasesym_kurtosis_WL3_N5  \
0                                         63.183181   
1                                         52.634005   
2                                         16.277217   
3                                         38.600415   
4                                         23.831176   

   PREDICT_original_phasef_phasesym_peak_WL3_N5  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   

   PREDICT_original_phasef_phasesym_peak_position_WL3_N5  \
0                   

In [264]:
y = data['label']
variables = data.drop(['label','ID'],axis=1)

In [265]:
data.var()

/var/folders/0z/tt67bwn10wx0s0569j48tb9h0000gn/T/ipykernel_86807/445316826.py:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.var()


PREDICT_original_sf_compactness_avg_2.5D                       0.017328
PREDICT_original_sf_compactness_std_2.5D                       0.005449
PREDICT_original_sf_rad_dist_avg_2.5D                        480.356830
PREDICT_original_sf_rad_dist_std_2.5D                         15.135952
PREDICT_original_sf_roughness_avg_2.5D                        25.794623
                                                              ...      
PREDICT_original_phasef_phasesym_peak_position_WL3_N5          0.000000
PREDICT_original_phasef_phasesym_range_WL3_N5                  0.017380
PREDICT_original_phasef_phasesym_energy_WL3_N5            856454.184955
PREDICT_original_phasef_phasesym_quartile_range_WL3_N5         0.003078
PREDICT_original_phasef_phasesym_entropy_WL3_N5                5.076242
Length: 493, dtype: float64

In [266]:
from sklearn.feature_selection import VarianceThreshold
variance_tres = VarianceThreshold(0)
selection = variance_tres.fit(variables)
a = selection.get_support()

In [267]:
a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [268]:
dropped_columns_df = [column for column in variables.columns 
          if column not in variables.columns[a]]

In [269]:
dropped_columns_df

['PREDICT_original_tf_LBP_max_R3_P12',
 'PREDICT_original_tf_LBP_peak_R3_P12',
 'PREDICT_original_tf_LBP_peak_position_R3_P12',
 'PREDICT_original_tf_LBP_max_R8_P24',
 'PREDICT_original_tf_LBP_peak_position_R8_P24',
 'PREDICT_original_tf_LBP_max_R15_P36',
 'PREDICT_original_tf_LBP_peak_position_R15_P36',
 'PREDICT_original_phasef_phasecong_min_WL3_N5',
 'PREDICT_original_phasef_phasecong_peak_WL3_N5',
 'PREDICT_original_phasef_phasecong_peak_position_WL3_N5',
 'PREDICT_original_phasef_phasesym_min_WL3_N5',
 'PREDICT_original_phasef_phasesym_peak_WL3_N5',
 'PREDICT_original_phasef_phasesym_peak_position_WL3_N5']

In [270]:
high_variance = variables.drop(dropped_columns_df,axis=1)

In [271]:
index_label = list()

In [272]:
len_y = len(y)

In [273]:
for i in range(0,len_y):
    if y[i] == 'GIST':
        index_label.append(1)
    else:
        index_label.append(0)    

In [274]:
len(index_label)

246

In [275]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [276]:
X_train, X_test, y_train, y_test = train_test_split(high_variance,index_label, random_state = 0)

In [277]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000, random_state = 0)
rf.fit(X_train, y_train)


RandomForestClassifier(n_estimators=1000, random_state=0)

In [278]:
prediction = rf.predict(X_test)

In [279]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.6774193548387096

In [280]:
rf.feature_importances_

array([2.92542836e-03, 2.08845134e-03, 2.26282342e-03, 2.60054884e-03,
       2.57004669e-03, 1.50586820e-03, 1.68031741e-03, 2.49155509e-03,
       1.77348787e-03, 2.95959582e-03, 2.86725116e-03, 4.66813040e-03,
       2.21967224e-03, 3.48450736e-03, 4.12206231e-03, 3.74811751e-03,
       2.81896565e-03, 3.91162872e-03, 2.56444197e-03, 5.65180364e-03,
       1.96860388e-03, 3.64537922e-03, 3.34994333e-03, 4.44185004e-03,
       5.96267549e-03, 1.94493194e-03, 5.38885578e-03, 5.61606877e-03,
       3.00978418e-03, 2.22992425e-03, 1.75526964e-03, 4.50941898e-03,
       2.58146646e-03, 3.29943065e-03, 5.39205960e-03, 2.35587537e-03,
       1.88097568e-03, 1.96707844e-03, 2.66297969e-03, 2.21998938e-03,
       3.11863687e-03, 2.42389266e-03, 3.22560674e-03, 2.38972901e-03,
       3.30662362e-03, 1.90184286e-03, 2.35837777e-03, 1.43134045e-03,
       3.67200849e-03, 2.17138051e-03, 2.16516968e-03, 1.38218237e-03,
       2.57885203e-03, 2.65324522e-03, 2.57238783e-03, 3.30286511e-03,
      

In [281]:
from sklearn.feature_selection import SelectFromModel
model = SelectFromModel(rf, prefit=True)

In [282]:
Ffkutten = X_train
RFselected = model.transform(Ffkutten)

/Applications/miniconda3/lib/python3.8/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(


In [283]:
RFselected

array([[8.98569546e-01, 4.55677309e-02, 2.03288448e+01, ...,
        3.06199323e+01, 4.08427556e+01, 1.07328768e+01],
       [8.95112463e-01, 3.98108939e-02, 2.09898835e+01, ...,
        3.82840266e+01, 3.19374437e+01, 9.90242877e+00],
       [6.76224700e-01, 1.40164103e-01, 3.05672807e+01, ...,
        3.84177899e+01, 1.41490592e+02, 1.17780572e+01],
       ...,
       [5.82283826e-01, 2.20266336e-01, 7.26232969e+01, ...,
        1.20550535e+02, 1.77002378e+03, 1.43890850e+01],
       [7.23712788e-01, 9.47770571e-02, 4.33779393e+01, ...,
        1.00925900e+02, 1.29069517e+02, 1.23638120e+01],
       [7.78206841e-01, 1.11522688e-01, 1.90571254e+01, ...,
        5.02019148e+01, 9.06226605e+00, 7.83833471e+00]])

In [284]:
clf = Pipeline([
  ('feature_selection', SelectFromModel(LinearSVC(penalty="l1"))),
  ('classification', RandomForestClassifier())
])
clf.fit(X, y)

NameError: name 'LinearSVC' is not defined